### ISSUE TITLE
not working this cmd

### ISSUE THREAD

**Issue by Khushal2711** [LxaNce-Hacker/Wifi-Passwords#1]
I tried in power shell as administrator but not working.

![Screenshot (177)](https://github.com/LxaNce-Hacker/Wifi-Passwords/assets/60664416/daa1b999-9a34-4c99-a77e-083cdff4ed44)

**Comment by LxaNce-Hacker** [comment]
Please follow the instructions carefully
In WiFi-Passwords repository.
